--- #YAML:1.0
name:               cpandevel
version:            2.05
abstract:           CPAN Testers Development
author:
    - Barbie <barbie@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::IniFiles:  0
    File::Basename:    0
    File::Copy:        0
    File::Path:        0
    Getopt::ArgvFile:  0
    Getopt::Long:      0
    Number::Format:    0
    Template:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
