--- #YAML:1.0
name:                cpandevel
version:             2.02
abstract:            CPAN Testers Development
license:             ~
author:              
    - Barbie <barbie@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::IniFiles:              0
    File::Basename:                0
    File::Copy:                    0
    File::Path:                    0
    Getopt::ArgvFile:              0
    Getopt::Long:                  0
    Number::Format:                0
    Template:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
